### ISSUE TITLE
[Marketplace 20x ] Explore How to Query / Search

### ISSUE THREAD

**Issue by pisuthd** [tamago-finance/marketplace-scb10x#160]
20x is improved version of marketplace-10x which is a fully decentralized and unhackable utilized the IPFS storage to persists JSON instead of the traditional database. But we need to check how to do query / search with the new version we have.

Check out: /fontend-v2 on `marketplace-10x` repo

**Comment by Moopz-Dev** [comment]
Planning a scheme to implement IPFS at the moment
[https://drive.google.com/file/d/1Nd8LSu8PmRHm72NWZzhmcjTy-Dvk4M7d/view?usp=sharing](url)
