### ISSUE TITLE
[Marketplace 10x] Re-check Cross-chain Flow

### ISSUE THREAD

**Issue by pisuthd** [tamago-finance/marketplace-scb10x#31]
Just re-checking the flow for cross-chain swaps if there're issues or concerns in various scenarios such as:

- Buyer / seller cancel orders when the process is not completed.
- Multiple sellers swap at the same time.

Can check from both source code's test cases and UI.

**Comment by jomjamkusuma** [comment]
**สรุปความคิดเห็นที่เป็นไปได้**
seller = คน create order, buyer = คนกด buy
1. buyer แย่งกัน claim NFT 1 ชิ้นในเวลาเดียวกัน
2. เมื่อ buyer กด claim NFT แล้ว แต่ว่า seller กด cancel ระหว่างรอ transaction (ที่มีความล่าช้าแบบ cross-chain)
3. เมื่อ buyer กำลังจะกด claim NFT แต่ว่า seller กด cancel ก่อน
4. เมื่อมีการ create order จำนวนมาก ส่งผลให้ database ล่ม? contract ช้า?
5. ถ้า relayer/validator เจ๊ง มีปัญหา ไม่ส่งข้อมูลไปที่ contract จะเกิดอะไรขึ้น?

**Comment by pisuthd** [comment]
> **สรุปความคิดเห็นที่เป็นไปได้** seller = คน create order, buyer = คนกด buy
> 
> 1. buyer แย่งกัน claim NFT 1 ชิ้นในเวลาเดียวกัน
> 2. เมื่อ buyer กด claim NFT แล้ว แต่ว่า seller กด cancel ระหว่างรอ transaction (ที่มีความล่าช้าแบบ cross-chain)
> 3. เมื่อ buyer กำลังจะกด claim NFT แต่ว่า seller กด cancel ก่อน
> 4. เมื่อมีการ create order จำนวนมาก ส่งผลให้ database ล่ม? contract ช้า?
> 5. ถ้า relayer/validator เจ๊ง มีปัญหา ไม่ส่งข้อมูลไปที่ contract จะเกิดอะไรขึ้น?

1,4, will look into solutions to prevent these issues.
2,3. A buyer can't claim NFT at the seller chain. When this case happening, the buyer must fill-in the dispute form to let's admin returns his/her NFT.
5. None of buyers, sellers can buy or claim NFTs
